### PR TITLE
Separate initial project creation from setup of a new environment.

### PR DESCRIPTION
**Pull request by floretan**
Here's a proposal on how to address #144, some workarounds are needed to not require modifications to build.sh that wouldn't be compatible with older versions.

### CODE REVIEW

**Comment by tharna** [comment]
This looks good. And we should definitely use higher level commands in the site.yml context instead of hiding them in the build.sh (drush, composer and shell for example). That way it would be easier to understand without looking into build.sh code.
One think that I would still keep is the read only webroot ;)

**Comment by floretan** [comment]
Drupal forces us to have quite a few things, including pretty much all custom code, in the webroot. Making that read-only wouldn't work. We could eventually make the web/*/contrib read-only, as well as the vendor folder, but I see relatively little value in doing this in local environments.

**Comment by tharna** [comment]
Yes that is true for local. But we still should do it in other environments as well as backups.

**Comment by tharna** [comment]
nwm. missed one fold :D

**Comment by floretan** [comment]
Sorry I should have mentioned that, I removed the backup command as it was causing issues (that was caused by https://github.com/hechoendrupal/drupal-console/issues/3186, a fresh install includes the related PR, otherwise just run `composer update`). Now it would work. 

Why was the backup command run after the "make" command? Shouldn't we run it before or am I missing something?

**Comment by tharna** [comment]
Backup should be before in current model. In the old one it didn't matter as long as it was before the finalize step.
One more thing: lot's of people have already accustomed to using "new" to setup fresh environments, not setting up new project from scratch, so should we still keep that (no matter how counter-intuitive it might sound) and use something like "init" or "create" for the first time installation? Or should we jst make sure everybody gets the memo?

**Comment by floretan** [comment]
Backups are now run before composer install. The `new` command now points to the `create` and `reset` commands.

**Pull request merged**
