### PR TITLE
Make drupal build.sh optional for custom setups.

### PR DESCRIPTION
**Pull request by artursv**
In some cases one would like to use Wundertools as a base for a project but one might not necessarily need the drupal/build.sh script - for example project might not have site.make file or it's some kind of unique setup. So how about we make the download/update optional?

Here is a patch for a start.

### CODE REVIEW

**Comment by tharna** [comment]
This is a really good point, but I think the better aproach would be to add a parameter to project.yml and then checking against that. Then there is no need to answer the prompt every time running the update.

**Comment by artursv** [comment]
Yes, that's even better idea. Maybe something along the lines of 

```
buildsh:
  enabled: true
  branch: develop
  revision:
```

**Comment by tharna** [comment]
Exactly. Then you have $buildsh_enabled variable available in build.sh that you can check against.

**Comment by artursv** [comment]
Adjusted code accordingly.

**Pull request merged**
